openapi: 3.0.3
info:
  title: Sample API
  description: This is a sample API.
  contact:
    name: Test
servers:
  - url: 'http://api.example.com'
tags:
  - name: Sample
    description: This is a sample tag.
paths:
  /test:
    get:
      description: Get some test data.
      operationId: getTestData
      tags:
        - Sample
      security:
        - api_key: []
      parameters:
        - name: limit
          in: query
          description: How many items to return at one time (max 100)
          required: false
          schema:
            type: integer
            format: int32
            example: 1
        - name: min
          in: query
          description: min items to return
          required: true
          schema:
            type: integer
            format: int32
            example: 1
      responses:
        '200':
          description: OK
          headers:
            X-RateLimit-Limit:
              schema:
                type: integer
                example: 1
          content:
            application/json:
              schema:
                required:
                  - id
                  - name
                properties:
                  id:
                    type: integer
                    format: int64
                  name:
                    type: string
                  tag:
                    type: string
                example:
                  id: 1
                  name: tom
                  tag: man
        '500':
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /pets:
    post:
      description: Create a pet.
      operationId: createPet
      tags:
        - Sample
      security:
        - api_key: []
      requestBody:
        description: desc
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Pet'
      responses:
        '201':
          description: Created
          headers:
            X-RateLimit-Limit:
              schema:
                type: integer
                example: 1
          content:
            application/json:
              schema:
                required:
                  - id
                properties:
                  id:
                    type: integer
                    format: int64
                  name:
                    type: string
                  tag:
                    type: string
                example:
                  id: 1
                  name: tom
                  tag: man
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
components:
  schemas:
    Pet:
      required:
        - id
        - name
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        tag:
          type: string
    Pets:
      type: array
      items:
        $ref: '#/components/schemas/Pet'
    Error:
      required:
        - code
        - message
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string
      example:
        code: 2
        message: m
  securitySchemes:
    api_key:
      description: desc
      in: header
      name: api_key
      type: apiKey
    bearer:
      description: desc
      type: http
      scheme: bearer